package utils;

import java.util.ArrayList;
import java.util.List;

public class Klasse {

    public List<String> klassenStringToList = new ArrayList<>();

    public List<String> holeSchuelerVonString(){

        klassenStringToList.add(alleschueler5b);
        klassenStringToList.add(alleschueler6a);

        return klassenStringToList;
    }


    public String alleschueler5b = "\n" +
            "\n" +
            "1\n" +
            "Leo Aaron Frey\n" +
            "2\n" +
            "Beek\n" +
            "3\n" +
            "4.7.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Kristian\n" +
            "2\n" +
            "Djuric\n" +
            "3\n" +
            "18.2.2008\n" +
            "4\n" +
            "m\n" +
            "1\n" +
            "Yusuf\n" +
            "2\n" +
            "Dogan\n" +
            "3\n" +
            "31.1.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Mert\n" +
            "2\n" +
            "Doganay\n" +
            "3\n" +
            "20.1.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Deniz\n" +
            "2\n" +
            "Duman\n" +
            "3\n" +
            "18.2.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Nurullah\n" +
            "2\n" +
            "Durmisev\n" +
            "3\n" +
            "5.5.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Sirin\n" +
            "2\n" +
            "Kabazeh\n" +
            "3\n" +
            "15.1.2007\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Haci Ali\n" +
            "2\n" +
            "Kavzan\n" +
            "3\n" +
            "19.5.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Melisa\n" +
            "2\n" +
            "Kaya\n" +
            "3\n" +
            "16.5.2008\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Nicol-Gabriela\n" +
            "2\n" +
            "Marcu\n" +
            "3\n" +
            "3.8.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "1\n" +
            "Rade\n" +
            "2\n" +
            "Marinkovic\n" +
            "3\n" +
            "22.2.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Emel\n" +
            "2\n" +
            "Memedali\n" +
            "3\n" +
            "11.11.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Hakan\n" +
            "2\n" +
            "Özirikara\n" +
            "3\n" +
            "8.5.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Gamze\n" +
            "2\n" +
            "Sabanova\n" +
            "3\n" +
            "25.6.2008\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Tihomir\n" +
            "2\n" +
            "Saegebarth\n" +
            "3\n" +
            "11.9.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "-\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Aleyna Angelie\n" +
            "2\n" +
            "Sakirova\n" +
            "3\n" +
            "18.8.2007\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "1\n" +
            "Maria\n" +
            "2\n" +
            "Sciarratta\n" +
            "3\n" +
            "25.6.2008\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Marijan\n" +
            "2\n" +
            "Smailovic\n" +
            "3\n" +
            "17.9.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Muhammed Malik\n" +
            "2\n" +
            "Tekin\n" +
            "3\n" +
            "14.4.2008\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Iman\n" +
            "2\n" +
            "Zahid\n" +
            "3\n" +
            "2.10.2007\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n";


    public String alleschueler6a = "\n" +
            "1\n" +
            "Junus\n" +
            "2\n" +
            "Abd Elaal\n" +
            "3\n" +
            "30.03.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Mohamed\n" +
            "2\n" +
            "Almesreb\n" +
            "3\n" +
            "05.05.2005\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Alea\n" +
            "2\n" +
            "Anders\n" +
            "3\n" +
            "17.07.2007\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Mohamad\n" +
            "2\n" +
            "Asdo\n" +
            "3\n" +
            "13.09.2006\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "David\n" +
            "2\n" +
            "Barjamovic\n" +
            "3\n" +
            "18.07.2006\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Mohamad\n" +
            "2\n" +
            "Dahman\n" +
            "3\n" +
            "28.08.2005\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Zara\n" +
            "2\n" +
            "Durmiseva\n" +
            "3\n" +
            "23.04.2007\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "1\n" +
            "Bislan\n" +
            "2\n" +
            "Dzhavatkhanov\n" +
            "3\n" +
            "07.03.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Medine\n" +
            "2\n" +
            "Fazliova\n" +
            "3\n" +
            "22.08.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "1\n" +
            "Zoe Jeyleen Keyleen\n" +
            "2\n" +
            "Feiler Cobos\n" +
            "3\n" +
            "23.11.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Justin Jörg\n" +
            "2\n" +
            "Fenske\n" +
            "3\n" +
            "18.01.2006\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "B¸sra\n" +
            "2\n" +
            "Inan\n" +
            "3\n" +
            "23.11.2006\n" +
            "4\n" +
            "w\n" +
            "1\n" +
            "Berfin\n" +
            "2\n" +
            "Kittelmann\n" +
            "3\n" +
            "03.08.2007\n" +
            "4\n" +
            "w\n" +
            "1\n" +
            "Saned\n" +
            "2\n" +
            "Mohamed\n" +
            "3\n" +
            "05.01.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Kiwan\n" +
            "2\n" +
            "Mourad\n" +
            "3\n" +
            "21.03.2006\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Oskar Marcin\n" +
            "2\n" +
            "Nawrocki\n" +
            "3\n" +
            "05.06.2005\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Diarra\n" +
            "2\n" +
            "Ndiaye\n" +
            "3\n" +
            "27.03.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Raphael Ugochi\n" +
            "2\n" +
            "Oduku\n" +
            "3\n" +
            "20.03.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "\n" +
            "1\n" +
            "Junus Emre\n" +
            "2\n" +
            "Skenderovski\n" +
            "3\n" +
            "12.04.2007\n" +
            "4\n" +
            "m\n" +
            "\n" +
            "1\n" +
            "Berrin Amaliya\n" +
            "2\n" +
            "Tot Bagi\n" +
            "3\n" +
            "28.08.2006\n" +
            "4\n" +
            "w\n" +
            "\n" +
            "\n";
}